### ISSUE TITLE
Buscar por Nombre (PAGE 2)

### ISSUE THREAD

**Issue by mpabarca** [mpabarca/SCL007-hackathon-peliculas#16]

**Comment by DaniAntu** [comment]
Buscar por nombre está OK, trae la data con todas las películas coincidentes al nombre.

**Comment by mpabarca** [comment]
Se crea funcion getMoviesByName 
y se llama en el mismo DOM el root

**Comment by mpabarca** [comment]
Paz:
Al buscar una pelicula en el buscador desaparece toda la pantalla de inicio (carrusel + lista peliculas)

**Comment by mpabarca** [comment]
Paz:
Por volver responsive card

**Comment by mpabarca** [comment]
Paz: 
Por agregar circulo con mas para cambiar con detalles
FABs in cards

**Comment by mpabarca** [comment]
Paz:
Listo Responsive card dinámico + circulo con mas para cambiar con detalles
