### ISSUE TITLE
Login (PAGE 1)

### ISSUE THREAD

**Issue by mpabarca** [mpabarca/SCL007-hackathon-peliculas#18]

**Comment by mpabarca** [comment]
Paz:
Merge desde daniAntu se agrega login en navbar

**Comment by DaniAntu** [comment]
Se muestra mensaje de trabajamos para usted en opción "registro"

**Comment by DaniAntu** [comment]
> Paz:
> Merge desde daniAntu se agrega login en navbar

Agregando opción de Login
